---
title: "A Brief Introduction to Slack"
subtitle: "UIC BioS"
author: "Lucy Delaney"
version: "Version 3"
date: "`r Sys.Date()`"
output:
  html_document:
    template: ../input/templates/cb-html-template.html
    css:
      - ../input/dist/custom.min.css
      - ../input/dist/bootstrap.css
  pdf_document:
    latex_engine: xelatex
    template: ../input/templates/cb-latex-template.tex
    keep_tex: false
documentclass: "article"
fontsize: 11pt
geometry_opts: margin = 1.1in
web_link: "\\href{https://ledelaney.org/cb-materials/slack/BIOS-Slack-Overview.html}{click here for web version}"
my_toc:
  - {title: Requirements, link: requirements}
  - {title: Getting Started, link: getting-started}
  - {title: Channels, link: channels}
  - {title: Search Bar, link: search-bar}
  - {title: Replies and Feedback, link: replies-and-feedback}
  - {title: File Sharing, link: file-sharing}
  - {title: Direct Messaging, link: direct-messaging}
  - {title: More Resources, link: more-resources}
pdf_version_top: '<a class="dropdown-item"  href="https://drive.google.com/file/d/1LWHZB7ih3rSfW_l29KgtoEpxxtyeG13_/view?usp=sharing" target="_blank">Download PDF version</a>'
pdf_version_bottom: '<a href="https://drive.google.com/file/d/1LWHZB7ih3rSfW_l29KgtoEpxxtyeG13_/view?usp=sharing" target="_blank">Download PDF version</a>'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
#myoutput <- "latex"
myoutput <- "html"

popups <- function(mylink, output = myoutput){
  
  if(output == "latex"){
    a <- paste0("\\href{", mylink, "}", "{[View Screenshot]}") %>%
      noquote()
    return(a)
  }
  
  else if(output == "html"){
    b <- paste0('<a href="', mylink, '"', " ",
                'target="popup"', " ", 
                'onclick="', 
                "window.open('", mylink, "', 'popup','width=600,height=600'); return false;",
                '">', " ", "[View Screenshot]", "</a>") %>%
      noquote()
    return(b)
  }
  
}


smallfont <- function(mytext, output = myoutput){
  
  if(output == "latex"){
    a <- paste0("\\tiny{", mytext, "}") %>%
      noquote()
    return(a)
  }
  
  else if(output == "html"){
    b <- paste0('<span style = font-size:10px>', mytext, "</span>") %>%
      noquote()
    return(b)
  }
  
}


# <a href="https://kanishkkunal.in" 
#   target="popup" 
#   onclick="window.open('https://kanishkkunal.in','popup','width=600,height=600'); return false;">
#     [View Screenshot]
# </a>

#\href{}{}


latex.only <- function(mytext, output = myoutput){
  
  if(output == "latex"){
    b <- paste0(mytext) %>%
      noquote()
    return(b)
  }
  
  else if(output != "latex"){
    return(NULL)
    
  }
}

html.only <- function(mytext, output = myoutput){
  
  if(output == "html"){
    b <- paste0(mytext) %>%
      noquote()
    return(b)
  }
  
  else if(output != "html"){
    return(NULL)
    
  }
}

```


# Requirements

You can download the Slack app for your computer, phone, and/or tablet. 
One of the nicest features is being able move across devices easily. 
You will also need to create an account using an email and a password.

1. For your Mac computer, [download here.](https://slack.com/help/articles/207677868-Download-Slack-for-Mac){target="_blank"}
2. For your iPhone, [download here.](https://slack.com/help/articles/208401947-Download-Slack-for-iOS){target="_blank"}
3. For your Windows computer, [download here.](https://slack.com/help/articles/209038037-Download-Slack-for-Windows){target="_blank"}
4. For your Android device, [download here.](https://slack.com/help/articles/207691318-Download-Slack-for-Android){target="_blank"}

# Getting Started

Once you have downloaded the above apps and created a login, [click here to join our group's Slack workspace.](https://join.slack.com/t/biosteaching/shared_invite/zt-kxcy4mw0-XS~Rfko_lYnEgQYUoyqwpg)
(_Note: These links expire after 30 days. If it is past 2/6/2021, [email Lucy](mailto:ldelan5@uic.edu) for a fresh link._)

At the top right-hand corner of the desktop version, you'll see a small photo (your user photo).
Click here to edit your profile (click `edit profile`). 
`r popups(mylink = "https://ledelaney.org/cb-materials/slack/input/images/edit-slack-profile.png")`
You may want to change your display name or other details. 
You can also find `Preferences` here, which allow you to customize your `Notifications` and other settings.
`r popups(mylink = "https://ledelaney.org/cb-materials/slack/input/images/slack-notifications.png")`
There is an option to turn off notifications at certain times, or to only be notified under certain conditions.

# Channels

On the left panel, you'll notice a `Channels` area.
`r popups(mylink = "https://ledelaney.org/cb-materials/slack/input/images/slack-channels.png")`
Channels organize conversations related to specific topics. 
These are the channels available to us currently (but we can always add more):

1. **general.** This is for group-wide announcements and information. 
2. **bb-assessments.** This is a place to chat about quizzes, tests, or assignments on Blackboard.
3. **bb-technical.** Blackboard technical issues and errors can be discussed here.
4. **collaborate-help.** Issues with or questions relating to Blackboard Collaborate.
4. **materials.** Helpful materials for teaching online or working with Blackboard or other online software.
5. **panopto-help.** For issues relating to Panopto lectures or embedded Panopto quizzes.
6. **random.** General chitter-chatter not work-related.

Post your questions in the channel that most resembles their topic, or search through a channel relevant to information you need. 
If you don't wish to be a part of a channel, you can right-click on the channel itself and `mute` it or `leave` it entirely.
`r popups(mylink = "https://ledelaney.org/cb-materials/slack/input/images/slack-mute-channel.png")`

# Search Bar

Before you ask a question in a channel, use the search bar located on the very top of the Slack app to see if your question has already been answered. 
Once you search a specific term, you'll see all messages, channels, or individuals that match that search term. 
If you see a post that looks helpful, click on it to be transported to that space in Slack.

# Replies and Feedback 

Slack can quickly get messy and difficult to navigate. 
To keep things organized, pay attention to a few things:

1. If you wish to reply to a specific post, hover over that post and `Create Thread`. This will keep all posts and relevant replies organized together.
`r popups(mylink = "https://ledelaney.org/cb-materials/slack/input/images/slack-thread.png")`
2. Take advantage of non-verbal feedback (emoji responses) to react to posts or let people know you've seen them -- this will keep the channel clear for those that wish to search it for relevant information!
`r popups(mylink = "https://ledelaney.org/cb-materials/slack/input/images/slack-emoji.png")`
3. If you want to ensure a specific person sees your post, use the `@` symbol to tag that individual in your post or reply.
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/slack-at.png")`

Once you've posted something, you may edit or delete it by hovering over the message and pressing the vertical `...` (or clicking on it in your phone) and selecting either of those options.
`r popups(mylink = "https://ledelaney.org/cb-materials/slack/input/images/slack-edit-message.png")`

# File Sharing 

Files can be "dropped" into Slack in two ways:

1. Press the paperclip symbol on the bottom right-hand side of the messaging area and browse for the file.
2. Drag and drop the file into the messaging area.

Write a relevant description of what the file is so that people may search for it. 
Files can generally be previewed in Slack, but they can also be downloaded by hovering over the file and selecting `Download` in the upper right-hand corner.

Files are also located in the menu item `File Browser` if you wish to see all files available within the Slack workspace.
`r popups(mylink = "https://ledelaney.org/cb-materials/slack/input/images/slack-file-browse.png")`

# Direct Messaging

You may privately message individuals or a small group of individuals (up to 7) in the Slack workspace. 
In the `Direct Messages` area, press the $+$ symbol and search for the person you wish to message. 
If you can't remember their name, you can find them in by searching the `People and User Groups` menu area on the top left-hand panel.

# More Resources

+ [Video tour of Slack](https://drive.google.com/file/d/1otltPSIP3Brabtu88iupECe6bDBB-3zW/view?usp=sharing){target="_blank"}
+ [Slack for beginners YouTube Video](https://www.youtube.com/watch?v=7YUTc4Cigc8&ab_channel=Howfinity){target="_blank"}
+ [Slack tutorial webpage](https://slack.com/resources/using-slack/how-to-use-slack){target="_blank"}

