---
title: "Copying Materials Between Bb Courses"
output:
  html_document:
    theme: cosmo
    highlight: tango
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Copy a Course

1. Enter the **older** Blackboard course that has content you want to copy.
2. On the left-hand menu panel, expand the `Packages and Utilities` section and click `Course Copy`. [View screenshot]
3. Select the option: `Copy Course Materials into an Existing Course`. [View screenshot]
4. In the Destination Course ID box click the Browse button to view a list of your courses. [View screenshot]
4a. In the popup window that appears, select the appropriate course ID from your list of courses and click Submit. The course ID will populate in the Destination Course ID Box. [View screenshot]
6. Select the course materials that you want to copy over to the existing course. `Select All` is generally recommended but not necessary.
7. In the `File Attachments` section, select `Copy links and copies of the content`
8. **DO NOT** select `Include Enrollments` in the Copy.
9. Click Submit.

# Copy a Test or Quiz

# Copy or Move Items & Folders


<span style = font-size:10px>  Yadda blah yadda. </span>