---
title: "Add Users to Blackboard Courses"
subtitle: "UIC BioS"
author: "L E Delaney"
version: "Version 3"
date: January 12, 2020
output:
  pdf_document:
    latex_engine: xelatex
    template: ../input/templates/cb-latex-template.tex
    keep_tex: false
  html_document:
    template: ../input/templates/cb-html-template.html
    css:
      - ../input/dist/custom.min.css
      - ../input/dist/bootstrap.css
geometry_opts: "margin=1.3in"
web_link: "\\href{https://ledelaney.org/cb-materials/blackboard/BIOS-Bb-AddMe.html}{click here for web version}"
my_toc:
  - {title: Add an Individual to a Bb Course, link: add-an-individual-to-a-bb-course}
  - {title: Blackboard Roles, link: blackboard-roles}
  - {title: Giving Access to Students Past Availability Window, link: giving-access-to-students-past-availability-window}
  - {title: More Resources, link: more-resources}
pdf_version_top: '<a class="dropdown-item"  href="https://drive.google.com/file/d/12sLbclS8GmG8gvVH8lsnuOdNKoh1ZXqR/view?usp=sharing" target="_blank">Download PDF version</a>'
pdf_version_bottom: '<a href="https://drive.google.com/file/d/12sLbclS8GmG8gvVH8lsnuOdNKoh1ZXqR/view?usp=sharing" target="_blank">Download PDF version</a>'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
myoutput <- "latex"
#myoutput <- "html"

popups <- function(mylink, output = myoutput){
  
  if(output == "latex"){
    a <- paste0("\\href{", mylink, "}", "{[View Screenshot]}") %>%
      noquote()
    return(a)
  }
  
  else if(output == "html"){
    b <- paste0('<a href="', mylink, '"', " ",
                'target="popup"', " ", 
                'onclick="', 
                "window.open('", mylink, "', 'popup','width=600,height=600'); return false;",
                '">', " ", "[View Screenshot]", "</a>") %>%
      noquote()
    return(b)
  }
  
}


smallfont <- function(mytext, output = myoutput){
  
  if(output == "latex"){
    a <- paste0("\\tiny{", mytext, "}") %>%
      noquote()
    return(a)
  }
  
  else if(output == "html"){
    b <- paste0('<span style = font-size:10px>', mytext, "</span>") %>%
      noquote()
    return(b)
  }
  
}


# <a href="https://kanishkkunal.in" 
#   target="popup" 
#   onclick="window.open('https://kanishkkunal.in','popup','width=600,height=600'); return false;">
#     [View Screenshot]
# </a>

#\href{}{}

latex.only <- function(mytext, output = myoutput){
  
  if(output == "latex"){
    b <- paste0(mytext) %>%
      noquote()
    return(b)
  }
  
  else if(output != "latex"){
    return(NULL)
    
  }
}

html.only <- function(mytext, output = myoutput){
  
  if(output == "html"){
    b <- paste0(mytext) %>%
      noquote()
    return(b)
  }
  
  else if(output != "html"){
    return(NULL)
    
  }
}

```

# Add an Individual to a Bb Course

1. Enter the Blackboard course where you wish to add the user.
2. On the left-hand menu panel under `Course Management`, expand the `Users and Groups` section and click `Users`.
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/users-groups.png")`
3. Select the option `Find Users to Enroll`.
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/users-to-enroll.png")`
4. In the `Username` box, **type in the username** of the individual you wish to add. (The browse feature does not always work.) `r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/enroll-screen.png")`
5. Select a `Role` for the individual. (See section below on `Blackboard Roles` for more information on what these designations allow.)
    + If you wish to add me to your course, please select `Teaching Assistant` or `Instructor` from the `Role` dropdown menu. If you are requesting that I move materials between courses, **please make sure to add me to all relevant courses**!
6. Select `Yes` or `No` for `Enrollment Availability`. (`Yes` is almost always the correct option.)
    + If you are adding a `Teaching Assistant`, `Course Builder`, or `Instructor`, these roles will have access to the course regardless of whether or not it is hidden. Thus, you can keep `Yes` selected and these individuals can still access a hidden course.
    + If you are adding a `Student`, selecting `Yes` means that the student can see the course only when it is made available by the instructor and/or during the normal availability period.
7. `Availability Override Date` should be left blank, unless you are adding a `Student` to a course that has already ended. See section on `Giving Access to Students Past Availability Window` below.
8. Click `Submit`.

## Blackboard Roles

+ Instructor
    + Instructors have access to all areas in the `Control Panel`. This role develops, teaches, or facilitates the class. Instructors can access a course that is unavailable to students. In addition, an instructor can export a Blackboard site as a court cartridge and can import a course cartridge. **Once an instructor is added to a course, only an administrator (i.e., LTS) can remove them.**
+ Student
    + Student is the default course role. Students have no access to the `Control Panel`.
+ Teaching Assistant
    + Teaching assistants can administer all areas of a course. A teaching assistant cannot delete an instructor (or another teaching assistant) from a course. Teaching assistants have access to most tools and features in the `Control Panel`. Even if a course is unavailable to students, teaching assistants still have access to the course. 
+ Course Builder
    + The course builder role has access to most areas of the `Control Panel`. This role is appropriate for a user to manage the course without having access to student grades. A course builder can still access the course if the course is unavailable to students. Course builders have access to the following Control Panel sections: `Content Collection`, `Course Tools`, `Users and Groups`, `Customization`, ` Packages and Utilities`, and `Help`.
+ Grader
    + A grader assists the instructor in the creation, management, delivery, and grading of items such as tests and discussion board posts. A grader also assists the instructor with managing the `Grade Center`. A grader cannot access a course if it is unavailable to students.Graders have access to the following `Control Panel` sections: `Content Collection`, `Course Tools`, `Evaluation`, `Grade Center`, `Users and Groups`, `Customization`, ` Packages and Utilities` (limited), and `Help`.
+ Guest 
    + Guests have no access to the Control Panel. They do not have access to content within a course unless the instructor designates certain content areas as available to `Guests`. The Guest role does not permit interaction in the Blackboard course and cannot give access to areas that display student information (e.g., `Discussion Board`, `Blogs`). If you wish to give auditors or guests access to all the content posted in your Blackboard course, add them with the `Student` role. More information on using this role is available here [Guest Access to a Blackboard Course](https://blackboard.ku.edu/guest-access).


# Giving Access to Students Past Availability Window 

Occassionally, you may have a student that needs access to a course that has already ended. (This may happen if the student takes an incomplete.) To give the student access to the course past the Enrollment Availability window, follow the procedure below.

1. Navigate to the old course in Blackboard where you wish to add the student.
2. Make sure that you have all relevant information for the student saved: Grade Center data, past Assignments, etc.
3. On the left-hand menu panel under `Course Management`, expand the `Users and Groups` section and click `Users`.
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/users-groups.png")` 
4. Find the student's username. If the course is large, I recommend selecting `Show All` at the bottom of the screen and using `Ctrl+F` to search for their name.
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/show-all-users.png")`
5. Click the grey caret adjacent to the student's username and select `Remove Users From This Course`. A pop-up appears: `This action is final and cannot be undone. Delete users?` Select `OK`.
    + The reason the student needs to be deleted first is because an availability date cannot be added once the student is already in the course. Bb allows the selection `Yes` or `No` for `Enrollment Availability`, but without the date specified, the student still can't access the course. The only time the availability date can be selected is when the user is **first** added.
6. Select the option `Find Users to Enroll`.
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/users-to-enroll.png")`
4. In the `Username` box, **type in the username** of the individual you wish to add.  
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/enroll-screen.png")`
5. Select a `Role` for the individual. In this case, `Student`.
6. Under `Availability Override Date` select the date that the student should no longer have access to the course. (So, if the date selected is 10/31/2021, the student would be able to see the course until that date, but not after.)

# More Resources

+ [KU resources for Users and Groups](https://blackboard.ku.edu/users-and-groups){target="_blank"}

