---
title: "Copying Materials Between Bb Courses"
subtitle: "UIC BioS"
author: "L E Delaney"
version: "Version 2"
date: January 12, 2020
output:
  pdf_document:
    latex_engine: xelatex
    template: ../input/templates/cb-latex-template.tex
    keep_tex: false
  html_document:
    template: ../input/templates/cb-html-template.html
    css:
      - ../input/dist/custom.min.css
      - ../input/dist/bootstrap.css
geometry_opts: margin=1in
documentclass: "article"
web_link: "\\href{https://ledelaney.org/cb-materials/blackboard/BIOS-Bb-CopyMoveMaterials.html}{click here for web version}"
my_toc:
  - {title: Copy a Course, link: copy-a-course}
  - {title: Copy a Test or Quiz, link: copy-a-test-or-quiz}
  - {title: Copy or Move Items and Folders, link: copy-or-move-items-and-folders}
  - {title: More Resources, link: more-resources}
pdf_version_top: '<a class="dropdown-item"  href="https://drive.google.com/file/d/1yjwJndAd-seWwwN1hB-UqEaKSH2mxBf9/view?usp=sharing" target="_blank">Download PDF version</a>'
pdf_version_bottom: '<a href="https://drive.google.com/file/d/1yjwJndAd-seWwwN1hB-UqEaKSH2mxBf9/view?usp=sharing" target="_blank">Download PDF version</a>'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
myoutput <- "latex"
#myoutput <- "html"

popups <- function(mylink, output = myoutput){
  
  if(output == "latex"){
    a <- paste0("\\href{", mylink, "}", "{[View Screenshot]}") %>%
      noquote()
    return(a)
  }
  
  else if(output == "html"){
    b <- paste0('<a href="', mylink, '"', " ",
                'target="popup"', " ", 
                'onclick="', 
                "window.open('", mylink, "', 'popup','width=600,height=600'); return false;",
                '">', " ", "[View Screenshot]", "</a>") %>%
      noquote()
    return(b)
  }
  
}


smallfont <- function(mytext, output = myoutput){
  
  if(output == "latex"){
    a <- paste0("\\tiny{", mytext, "}") %>%
      noquote()
    return(a)
  }
  
  else if(output == "html"){
    b <- paste0('<span style = font-size:10px>', mytext, "</span>") %>%
      noquote()
    return(b)
  }
  
}


# <a href="https://kanishkkunal.in" 
#   target="popup" 
#   onclick="window.open('https://kanishkkunal.in','popup','width=600,height=600'); return false;">
#     [View Screenshot]
# </a>

#\href{}{}

latex.only <- function(mytext, output = myoutput){
  
  if(output == "latex"){
    b <- paste0(mytext) %>%
      noquote()
    return(b)
  }
  
  else if(output != "latex"){
    return(NULL)
    
  }
}

html.only <- function(mytext, output = myoutput){
  
  if(output == "html"){
    b <- paste0(mytext) %>%
      noquote()
    return(b)
  }
  
  else if(output != "html"){
    return(NULL)
    
  }
}

```

# Copy a Course

1. Enter the **older** Blackboard course that has content you want to copy.
2. On the left-hand menu panel, expand the `Packages and Utilities` section and click `Course Copy`.
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/package-util.png")`
3. Select the only option: `Copy Course Materials into an Existing Course`. 
4. In the `Destination Course ID` box click the Browse button to view a list of your courses. 
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/destination-course.png")`
    + In the popup window that appears, select the appropriate course ID from your list of courses and click `Submit`. The course ID will populate in the `Destination Course ID Box`. You may also copy this destination ID and paste it in the box. `r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/copy-options.png")`
6. Select the course materials that you want to copy over to the existing course. `Select All` is generally recommended but not necessary. 
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/copy-options.png")`
7. In the `File Attachments` section, select `Copy links and copies of the content` 
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/file-attachments.png")`
8. **DO NOT** select `Include Enrollments` in the Copy.
9. Click `Submit`.

# Copy a Test or Quiz

_Please note: If the `Test` also has an associated `Pool`, the `Pool` will be automatically imported along with the `Test`. Even if the `Pool` is imported first, an additional `Pool` containing the `Test` questions will **also** be imported!_

First, export the test from the current course:

1. Navigate to the course that contains the test.
2. Click `Course Tools` in the left-hand menu panel. 
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/tests-survey-pools.png")`
3. Ensure the `Edit Mode` is ON, found at the top-right of your course window.
4. Click `Tests, Surveys, and Pools`. 
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/tests-survey-pools.png")`
5. Click `Tests`.
6. Click the grey caret to the right of the test name. 
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/export-test.png")`
7. Select `Export`
    + If you choose to `Export to Content Collection`, you can select `Browse` and navigate to `Course Content` in the menu panel and select the destination course. (All of your Bb courses should appear here, but it may require some scrolling!) `r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/export-content-collection.png")`
    + If you choose `Export to Local Computer`, you can download the .zip file to your computer. `r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/export-local.png")`
    

Next, import the test into the course of your choice:

1. Navigate to the Blackboard course where you will add the test.
2. Click `Course Tools` in the left-hand menu panel. 
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/tests-survey-pools.png")`
3. Ensure the `Edit Mode` is ON, found at the top-right of your course window.
4. Click `Tests, Surveys, and Pools`. 
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/tests-survey-pools.png")`
5. Click `Tests`.
6. Click `Import Test`. `r popups(mylink = "input/images/import-test.png")`
    + If you chose `Export to Content Collection`, select `Browse Content Collection` and look for the recently added `Test` file. `r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/browse-content.png")`
    + If you chose `Export to Local Computer`, select `Browse Local Files` and choose the .zip file you previously downloded.
7. Click `Submit`.
8. Click `OK`.

# Copy or Move Items and Folders

_Note: You may copy over assignments by navigating to `Packages and Utilities` $\rightarrow$ `Course Copy` and selecting only the folder(s) containing the relevant assignment._

1. Ensure the `Edit Mode` is ON, found at the top-right of your course window.
2. Click the grey caret to the right side of item/folder name. 
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/copy-move-item.png")`
3. Select `Copy` or `Move`. (You may also create a copy of the item, and then move the copy.) 
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/copy-move-item.png")`
4. Use the `Destination Course` drop down menu to select the course where the item will go. 
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/move-destination.png")`
5. Click the `Destination Folder` Browse button.
6. Select the area in the course you would like to place the item or folder in. You may need to click the Plus Sign (+ button) to find a folder within a folder. 
`r popups(mylink = "https://ledelaney.org/cb-materials/blackboard/input/images/move-folder.png")`
7. Select `No` for the option `Create links for items which cannot be copied`.
8. Click `Submit`.

# More Resources

+ [KU resources for copying and moving content in Bb](https://blackboard.ku.edu/copying-course-content){target="_blank"}
+ [YouTube video showing copying and moving content in Bb](https://www.youtube.com/watch?v=dO-IjSiiY1M&ab_channel=SDWTechnologyIntegrator){target="_blank"} (looks slightly different but same procedure!)