---
title: "Panopto for Student Assignments"
subtitle: "UIC BioS"
author: "Lucy Delaney"
version: "Version 1"
date: "`r Sys.Date()`"
output:
  html_document:
    template: ../input/templates/cb-html-template.html
    css:
      - ../input/dist/custom.min.css
      - ../input/dist/bootstrap.css
  pdf_document:
    latex_engine: xelatex
    template: ../input/templates/cb-latex-template.tex
    keep_tex: false
documentclass: "article"
fontsize: 11pt
linestretch: 1.1
geometry_opts: margin = 1.2in
web_link: "\\href{https://ledelaney.org/cb-materials/panopto/BIOS-Panopto-Assignment.html}{click here for web version}"
my_toc:
  - {title: Creating Panopto Video Assignments in Blackboard, link: creating-panopto-video-assignments-in-blackboard}
  - {title: Grading Panopto Video Assignments in Blackboard, link: grading-panopto-video-assignments-in-blackboard}
  - {title: All About Student Submission, link: student-submission}
  - {title: Watching or Discussing Student Submissions, link: watching-or-discussing-student-submissions}
  - {title: More Resources, link: more-resources}
pdf_version_top: '<a class="dropdown-item"  href="https://drive.google.com/file/d/1VVxAe3BktdQct7XS31ZoS6h526UBCytj/view?usp=sharing" target="_blank">Download PDF version</a>'
pdf_version_bottom: '<a href="https://drive.google.com/file/d/1VVxAe3BktdQct7XS31ZoS6h526UBCytj/view?usp=sharing" target="_blank">Download PDF version</a>'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
#myoutput <- "latex"
myoutput <- "html"

popups <- function(mylink, output = myoutput){
  
  if(output == "latex"){
    a <- paste0("\\href{", mylink, "}", "{[View Screenshot]}") %>%
      noquote()
    return(a)
  }
  
  else if(output == "html"){
    b <- paste0('<a href="', mylink, '"', " ",
                'target="popup"', " ", 
                'onclick="', 
                "window.open('", mylink, "', 'popup','width=600,height=600'); return false;",
                '">', " ", "[View Screenshot]", "</a>") %>%
      noquote()
    return(b)
  }
  
}


smallfont <- function(mytext, output = myoutput){
  
  if(output == "latex"){
    a <- paste0("\\tiny{", mytext, "}") %>%
      noquote()
    return(a)
  }
  
  else if(output == "html"){
    b <- paste0('<span style = font-size:10px>', mytext, "</span>") %>%
      noquote()
    return(b)
  }
  
}


# <a href="https://kanishkkunal.in" 
#   target="popup" 
#   onclick="window.open('https://kanishkkunal.in','popup','width=600,height=600'); return false;">
#     [View Screenshot]
# </a>

#\href{}{}


latex.only <- function(mytext, output = myoutput){
  
  if(output == "latex"){
    b <- paste0(mytext) %>%
      noquote()
    return(b)
  }
  
  else if(output != "latex"){
    return(NULL)
    
  }
}

html.only <- function(mytext, output = myoutput){
  
  if(output == "html"){
    b <- paste0(mytext) %>%
      noquote()
    return(b)
  }
  
  else if(output != "html"){
    return(NULL)
    
  }
}

```

`r latex.only("\\newpage")`

For information on setting up Panopto in Blackboard and general use, see the [Panopto Overview document](https://ledelaney.org/cb-materials/panopto/BIOS-Panopto-Overview.html).

**Note:** For students to submit videos, the `Panopto Video tool link` must be visible to them on the left-hand menu panel.

# Creating Panopto Video Assignments in Blackboard

Navigate to the area in Blackboard where you wish to deploy your assignment. On the top menu, hover over `Assessments` and select `Assignment`. 
`r popups("https://ledelaney.org/cb-materials/panopto/input/images/create-assignment.png")`
Select the $+$ button from inside the assignment editing page.
`r popups("https://ledelaney.org/cb-materials/panopto/input/images/add-panotpo.png")`
Select `Panopto Student Video Submission`.
This automatically writes out the steps for your students to submit their videos. The steps are as follows:

+ **Step 1**: Record or upload your video in Panopto. To start creating your video, click here to open your personal folder (For this link to work for students, Panopto Content must be unhidden!).
+ **Step 2**: Open the assignment in Blackboard and select Write Submission.
+ **Step 3**: In the text editor, expand Mashups and select Panopto Student Video Submission.
+ **Step 4**: A window will open to show the videos in your personal folder. If your video is located in a different folder, select the correct folder from the drop-down at the top.
+ **Step 5**: Select the video you wish to submit and click Insert.
+ **Step 6**: Your video will be added to the submission. Add any extra information and Submit.

Fill out the other details of your assignment as normal. For more information on creating Blackboard assignments, [click here](https://ledelaney.org/cb-materials/blackboard/BIOS-Bb-Assignments.html).

# Grading Panopto Video Assignments in Blackboard

To grade student submissions, head to Grade Center and find the appropriate Grade Center column for the assignment. Ungraded assignments will display a yellow exclamation point. You can either select the grey caret next to the yellow exclamation point of a particular student's assignment and select the `Attempt` to grade.
`r popups("https://ledelaney.org/cb-materials/panopto/input/images/grade-student.png")`
You may also select the grey caret next to the assignment name and select `Grade Attempts`.
`r popups("https://ledelaney.org/cb-materials/panopto/input/images/grade-all-attempts.png")`

Once inside a student's submission, the video will appear as a clickable link.
`r popups("https://ledelaney.org/cb-materials/panopto/input/images/student-sub.png")`
Clicking the link will launch Panopto in a new window, where you may view the student's video.
To leave feedback and a grade for the student, navigate back to the assignment tab and use the right-hand panel.
`r popups("https://ledelaney.org/cb-materials/panopto/input/images/feedback.png")`
Click submit.

# Student Submission

Every UIC student has a Panopto video account and can use this account to create videos. The easiest way for the student to access their personal folder is through the link provided in the assignment itself. This link will create a personal folder for the student if they don't already have one. From this folder, they can upload or create the assignment video.

## Creating student videos

Students have two options: they can use the Panopto software to create their video, or they can record the video in another program like Zoom.

To use the Panopto software, the students will select `Create` $\rightarrow$ `Record a New Session` from inside their Panopto folder. If they have not previously downloaded the Panopto program, they will be prompted to do so at this point.

To use Zoom, they can begin a Zoom meeting and select `Record the meeting to this computer`. Once finished, they will end the Zoom meeting and wait for the video conversion to finish. They will then select `Create` $\rightarrow$ `Upload media` from inside their Panopto folder. They will upload only the `.mp4` video to Panopto.

## Submitting student videos

Once the video is created and uploaded to the Panopto folder, students will select the `Write Submission` button from inside the Assignment itself. 
`r popups("https://ledelaney.org/cb-materials/panopto/input/images/write-submission.png")`
This will expand the text editor where the assignment is added. Next, they will need to expand the toolbar by selecting the three dots `...`.
`r popups("https://ledelaney.org/cb-materials/panopto/input/images/write-submission-full.png")`
From there, they will select the $+$ and `Panopto Student Video Submission`.

The student's Panopto folder will open and they can select the appropriate video. Whatever the video currently named will be what appears within the assignment as a link. More text can be added to the submission.
`r popups("https://ledelaney.org/cb-materials/panopto/input/images/student-write.png")`
Students will receive an email confirmation when they successfully submit the assignment.

**Note:** A copy of the video submission will be sent to a folder called Student Submissions that the instructor can access, and the original will remain in the student's personal folder. Once the assignment is submitted, students are unable to manage or edit the video submission.

# Watching or Discussing Student Submissions

Often instructors would like to share student videos in the class and have others comment on them or discuss. To do this, videos need to be moved to a separate folder inside of Panopto and deployed to a content area in Blackboard.

## Making videos available

All student videos will be added to a folder inside of `Panopto Content` called `Student Submissions`.
`r popups("https://ledelaney.org/cb-materials/panopto/input/images/student-sub-folder.png")`

Create a new folder in `Panopto Content` by selecting `Create` $\rightarrow$ `New Folder`.
`r popups("https://ledelaney.org/cb-materials/panopto/input/images/student-sub-folder.png")`
Give the folder a name. Make sure that the course folder is listed as the `parent folder`, and that the box is selected to inherit permissions from the parent folder.
`r popups("https://ledelaney.org/cb-materials/panopto/input/images/folder-opts.png")`

Once the public folder is created, you can move the student submissions to it by hovering over the video and selecting `Settings`. In `Overview`, click the `Folder` button to move to a different folder. Make sure that `Allow viewers to post comments` is checked.
`r popups("https://ledelaney.org/cb-materials/panopto/input/images/change-folder.png")`

Finally, navigate to the area in Blackboard where you want the student videos to appear. Hover over `Build Content` $\rightarrow$ `Panopto Video Embed`. You can change the folder from the top of the Panopto screen, and select student videos to deploy in Blackboard.

## Public discussion in videos

Students should select the option to view the video from inside of Panopto.
`r popups("https://ledelaney.org/cb-materials/panopto/input/images/watch-in-pan.png")`
On the left-hand side, there is a menu item called `Discussion`.
Anyone can type in notes or a comment that can be publicly viewed by all.
More information on moderating and downloading discussions [can be found here](https://support.panopto.com/s/article/How-to-Use-Discussions-in-Videos){target="_blank"}.


# More Resources

+ [Panopto resources on creating Bb Assignments](https://support.panopto.com/s/article/Assignment-Submission-Workflow-in-Blackboard){target="_blank"}
+ [Panopto resources for students on submitting video assignments](https://support.panopto.com/s/article/How-to-Submit-a-Video-Assignment-in-Blackboard){target="_blank"}
+ [Panopto resources on video discussion](https://support.panopto.com/s/article/How-to-Use-Discussions-in-Videos){target="_blank"}
+ [Comprehensive Panopto video overview](https://ledelaney.org/cb-materials/panopto/BIOS-Panopto-Overview.html){target="_blank"}
+ [Tutorial video for Panopto](https://drive.google.com/file/d/1bUKi5K7-V7cqmFHDtFhVPP-epq0S0b6o/view?usp=sharing){target="_blank"}
+ [ACCC Panopto quick-guide](https://uofi.app.box.com/s/39x6jxlqptj8dum88qqo4c4z4uo9881g){target="_blank"}


